name: 🐛 Bug Report
description: Create a report to help us improve Nixpacks.
title: "bug: "
labels: ["bug"]
body:
  - type: checkboxes
    id: issue-already-exists
    attributes:
      label: Is there an existing issue for this?
      description: |
        Please search to see if an issue already exists for the bug you encountered.
        Please see [Searching Issues and Pull Request](https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests) for how to use the GitHub search bar and filters.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: describe-the-bugs
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: Please provide a clear and concise description about the problem you ran into.
      placeholder: I ran into ... while using ...
  - type: textarea
    id: to-reproduce
    validations:
      required: false
    attributes:
      label: To reproduce
      description: |
        Please provide a code sample or a code snipet to reproduce said problem. If you have code snippets, error messages, stack trace please also provide them here.

        **IMPORTANT**: make sure to use [code tag](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) to correctly format your code. Screenshot is helpful but don't use it for code snippets as it doesn't allow others to copy-and-paste your code.
      placeholder: |
        Steps to reproduce the behaviour:

          1. Provide '...'
          2. Run '...'
          3. See error
  - type: textarea
    id: expected-behavior
    validations:
      required: false
    attributes:
      label: Expected behavior
      description: "A clear and concise description of what you would expect to happen."
  - type: textarea
    id: environment-info
    attributes:
      label: Environment
      description: |
        Please share your environment with us.
    validations:
      required: true
