name: Tag

on:
  push:
    branches:
      - main

jobs:
  tag:
    # Bot will commit new cargo version after release
    # Skip commits for cargo release as to not retrigger
    if: "!contains(github.event.head_commit.message, '(cargo-release)')"
    runs-on: ubuntu-latest
    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.1.2
        with:
          ref: ${{ github.ref }}
          running-workflow-name: CI
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.COMMITTER_TOKEN }}

      - run: git config --global user.email ${{ secrets.RAILWAY_BOT_EMAIL }}
      - run: git config --global user.name ${{ secrets.RAILWAY_BOT_NAME }}

      - uses: actions-ecosystem/action-get-merged-pull-request@v1
        id: pull-request
        with:
          github_token: ${{ secrets.COMMITTER_TOKEN }}

      - uses: actions-ecosystem/action-release-label@v1
        id: release-label
        if: ${{ steps.pull-request.outputs.title != null && !contains(steps.pull-request.outputs.labels, 'release/skip') }}
        with:
          github_token: ${{ secrets.GH_PAT }}
          labels: ${{ steps.pull-request.outputs.labels }}
      
      - uses: actions-rs/toolchain@v1
        if: ${{ !contains(steps.pull-request.outputs.labels, 'release/skip') }}
        with:
          toolchain: stable
      
      - uses: Swatinem/rust-cache@v2
        if: ${{ !contains(steps.pull-request.outputs.labels, 'release/skip') }}
      
      - run: cargo install cargo-release
        if: ${{ !contains(steps.pull-request.outputs.labels, 'release/skip') }}

      - uses: actions-rs/cargo@v1
        if: ${{ !contains(steps.pull-request.outputs.labels, 'release/skip') }}
        with:
          command: login
          args: ${{ secrets.NIXPACKS_CARGO_RELEASE_TOKEN }}
      
      - run: cargo release ${{ steps.release-label.outputs.level }} --execute --no-confirm
        if: ${{ !contains(steps.pull-request.outputs.labels, 'release/skip') }}
