name: Tag

on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    environment: Release
    name: Release
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: nash-ws/cargo-release-action@main
        with:
          major-label: major
          minor-label: minor
          patch-label: patch
          cargo-token: ${{ secrets.NIXPACKS_CARGO_RELEASE_TOKEN }}